[package]
name = "cargo-grip4rust"
version = "0.8.0"
edition = "2024"
rust-version = "1.85"
description = "A cargo subcommand for measuring Rust testability"
authors = ["Umberto Gotti <umberto.gotti@umbertogotti.dev>"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/umbgtt10/grip4rust"
keywords = ["cargo", "subcommand", "search", "grep", "cli"]
categories = ["development-tools::cargo-plugins", "command-line-utilities"]

autotests = false

[lib]
name = "grip"

[[test]]
name = "all_tests"
path = "tests/all_tests.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
tempfile = { workspace = true }
