// Copyright 2026 Umberto Gotti <umberto.gotti@umbertogotti.dev>
// Licensed under the MIT License
// SPDX-License-Identifier: MIT

pub const KNOWN_FOREIGN_TRAITS: &[&str] = &[
    "Display",
    "Debug",
    "Clone",
    "Default",
    "PartialEq",
    "Eq",
    "PartialOrd",
    "Ord",
    "Hash",
    "Into",
    "From",
    "TryFrom",
    "Drop",
    "Deref",
    "DerefMut",
    "Index",
    "IndexMut",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Rem",
    "Neg",
    "Not",
    "Fn",
    "FnMut",
    "FnOnce",
    "Send",
    "Sync",
    "Sized",
    "ToString",
    "AsRef",
    "AsMut",
    "Borrow",
    "BorrowMut",
    "Error",
    "Read",
    "Write",
    "Seek",
    "BufRead",
    "Iterator",
    "IntoIterator",
    "Future",
    "IntoFuture",
    "Serialize",
    "Deserialize",
];
